### ISSUE TITLE
Column having data type as Decimal are giving blank object in response JSON

### ISSUE THREAD

**Issue by rohankambli** [2Toad/node-teradata#40] opened 2018-02-15 14:22 UTC
Hi ,

We are facing issue with node-teradata plugin where when we perform read/ readPreparedStatement operation for table having columns of data type "DECIMAL" , the response JSON is giving blank object w,r,t those columns.

For example in table test, if column2 and column3 are of data type "DECIMAL" say DECIMAL(4,2) then 
if we execute select * from test the result response is coming as:

[
{
"column1" : 123,
"column2" : {
} // blank object
"column3" : {
} //blank object
"column4" : "abcd"
}
]

Can someone please help resolving this issue or suggest any workaround to get decimal values.

Thanks and Regards,
Rohan

**Comment by marsegliaandrea** [comment] 2018-04-06 12:41
@rohankambli If you haven't found a solution for this yet. I found this: [#155](https://github.com/CraZySacX/node-jdbc/issues/155). The issue is actually in node-jdbc library which node-teradata is using.  For workaround just paste this in the resultset.js line 125, between if and else statements:
`else if (type === 'BigDecimal') {
                result[cmd.label] = Number(self._rs[getter](i));
}`

For me this solved the same problem.

**Comment by JasonPierce** [comment] 2018-04-07 21:05
Thanks for sharing this workaround with the node-teradata community @marsegliaandrea.

Closing, since this is a node-jdbc issue.

**Closed as completed by JasonPierce** 2018-04-07 21:05 UTC
Labels: question
